////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by rawbuf. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __perf_test_20160818103831_h__
#define __perf_test_20160818103831_h__

#include "rawbuf.h"

namespace rawbuf {

struct perf_object_t
{
    bool bool_val;
    int8_t int8_val;
    uint8_t uint8_val;
    int16_t int16_val;
    uint16_t uint16_val;
    int32_t int32_val;
    uint32_t uint32_val;
    int64_t int64_val;
    uint64_t uint64_val;
    float float_val;
    double double_val;
    std::string str_val;
    std::vector<int32_t > vec_val;
    std::map<std::string, std::string > dict_val;

    void skip_bool_val() { __skip_bool_val = true; }
    void skip_int8_val() { __skip_int8_val = true; }
    void skip_uint8_val() { __skip_uint8_val = true; }
    void skip_int16_val() { __skip_int16_val = true; }
    void skip_uint16_val() { __skip_uint16_val = true; }
    void skip_int32_val() { __skip_int32_val = true; }
    void skip_uint32_val() { __skip_uint32_val = true; }
    void skip_int64_val() { __skip_int64_val = true; }
    void skip_uint64_val() { __skip_uint64_val = true; }
    void skip_float_val() { __skip_float_val = true; }
    void skip_double_val() { __skip_double_val = true; }
    void skip_str_val() { __skip_str_val = true; }
    void skip_vec_val() { __skip_vec_val = true; }
    void skip_dict_val() { __skip_dict_val = true; }

    bool rb_has_bool_val() const { return __rb_has_bool_val; }
    bool rb_has_int8_val() const { return __rb_has_int8_val; }
    bool rb_has_uint8_val() const { return __rb_has_uint8_val; }
    bool rb_has_int16_val() const { return __rb_has_int16_val; }
    bool rb_has_uint16_val() const { return __rb_has_uint16_val; }
    bool rb_has_int32_val() const { return __rb_has_int32_val; }
    bool rb_has_uint32_val() const { return __rb_has_uint32_val; }
    bool rb_has_int64_val() const { return __rb_has_int64_val; }
    bool rb_has_uint64_val() const { return __rb_has_uint64_val; }
    bool rb_has_float_val() const { return __rb_has_float_val; }
    bool rb_has_double_val() const { return __rb_has_double_val; }
    bool rb_has_str_val() const { return __rb_has_str_val; }
    bool rb_has_vec_val() const { return __rb_has_vec_val; }
    bool rb_has_dict_val() const { return __rb_has_dict_val; }

    perf_object_t();
    perf_object_t& operator=(const perf_object_t& obj_val);
    bool operator==(const perf_object_t& obj_val) const;
    rb_field_size_t rb_fields() const;
    rb_size_t rb_size() const;
    bool encode(rb_buf_t& buf) const;
    bool decode(const rb_field_table_item_t& item, const rb_buf_t& buf);

private:
    rb_field_id_t __id_bool_val;
    rb_field_id_t __id_int8_val;
    rb_field_id_t __id_uint8_val;
    rb_field_id_t __id_int16_val;
    rb_field_id_t __id_uint16_val;
    rb_field_id_t __id_int32_val;
    rb_field_id_t __id_uint32_val;
    rb_field_id_t __id_int64_val;
    rb_field_id_t __id_uint64_val;
    rb_field_id_t __id_float_val;
    rb_field_id_t __id_double_val;
    rb_field_id_t __id_str_val;
    rb_field_id_t __id_vec_val;
    rb_field_id_t __id_dict_val;

    bool __skip_bool_val;
    bool __skip_int8_val;
    bool __skip_uint8_val;
    bool __skip_int16_val;
    bool __skip_uint16_val;
    bool __skip_int32_val;
    bool __skip_uint32_val;
    bool __skip_int64_val;
    bool __skip_uint64_val;
    bool __skip_float_val;
    bool __skip_double_val;
    bool __skip_str_val;
    bool __skip_vec_val;
    bool __skip_dict_val;

    bool __rb_has_bool_val;
    bool __rb_has_int8_val;
    bool __rb_has_uint8_val;
    bool __rb_has_int16_val;
    bool __rb_has_uint16_val;
    bool __rb_has_int32_val;
    bool __rb_has_uint32_val;
    bool __rb_has_int64_val;
    bool __rb_has_uint64_val;
    bool __rb_has_float_val;
    bool __rb_has_double_val;
    bool __rb_has_str_val;
    bool __rb_has_vec_val;
    bool __rb_has_dict_val;
};

rb_size_t rb_sizeof(const perf_object_t& obj_val);
bool rb_encode(const perf_object_t& obj_val, rb_buf_t& rb_val);
bool rb_decode(const rb_buf_t& rb_val, rb_offset_t offset, perf_object_t& obj_val);
bool rb_dump(const perf_object_t& obj_val, const char * path);
bool rb_load(const char * path, perf_object_t& obj_val);

} // namespace rawbuf

#endif // __perf_test_20160818103831_h__