////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by rawbuf. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#include "perf_test.h"
#ifdef WIN32
#define true  1
#define false 0
#else
#include <stdbool.h>
#endif

void rb_init_perf_object(perf_object_t * obj_val)
{
    if (!obj_val)
    {
        return;
    }
    memset(obj_val, 0, sizeof(perf_object_t));

    rb_init_bool(&obj_val->bool_val);
    obj_val->id_bool_val = 0;
    obj_val->skip_bool_val = false;
    obj_val->rb_has_bool_val = false;

    rb_init_int8(&obj_val->int8_val);
    obj_val->id_int8_val = 1;
    obj_val->skip_int8_val = false;
    obj_val->rb_has_int8_val = false;

    rb_init_uint8(&obj_val->uint8_val);
    obj_val->id_uint8_val = 2;
    obj_val->skip_uint8_val = false;
    obj_val->rb_has_uint8_val = false;

    rb_init_int16(&obj_val->int16_val);
    obj_val->id_int16_val = 3;
    obj_val->skip_int16_val = false;
    obj_val->rb_has_int16_val = false;

    rb_init_uint16(&obj_val->uint16_val);
    obj_val->id_uint16_val = 4;
    obj_val->skip_uint16_val = false;
    obj_val->rb_has_uint16_val = false;

    rb_init_int32(&obj_val->int32_val);
    obj_val->id_int32_val = 5;
    obj_val->skip_int32_val = false;
    obj_val->rb_has_int32_val = false;

    rb_init_uint32(&obj_val->uint32_val);
    obj_val->id_uint32_val = 6;
    obj_val->skip_uint32_val = false;
    obj_val->rb_has_uint32_val = false;

    rb_init_int64(&obj_val->int64_val);
    obj_val->id_int64_val = 7;
    obj_val->skip_int64_val = false;
    obj_val->rb_has_int64_val = false;

    rb_init_uint64(&obj_val->uint64_val);
    obj_val->id_uint64_val = 8;
    obj_val->skip_uint64_val = false;
    obj_val->rb_has_uint64_val = false;

    rb_init_float(&obj_val->float_val);
    obj_val->id_float_val = 9;
    obj_val->skip_float_val = false;
    obj_val->rb_has_float_val = false;

    rb_init_double(&obj_val->double_val);
    obj_val->id_double_val = 10;
    obj_val->skip_double_val = false;
    obj_val->rb_has_double_val = false;

    rb_init_string(&obj_val->str_val);
    obj_val->id_str_val = 11;
    obj_val->skip_str_val = false;
    obj_val->rb_has_str_val = false;

    rb_init_int32_array(&obj_val->vec_val);
    obj_val->id_vec_val = 12;
    obj_val->skip_vec_val = false;
    obj_val->rb_has_vec_val = false;

    rb_init_string_dict(&obj_val->dict_val);
    obj_val->id_dict_val = 13;
    obj_val->skip_dict_val = false;
    obj_val->rb_has_dict_val = false;
}

rb_bool_t rb_set_perf_object(const perf_object_t * src, perf_object_t * dst)
{
    if (!src || !dst)
    {
        return false;
    }
    dst->id_bool_val = src->id_bool_val;
    dst->id_int8_val = src->id_int8_val;
    dst->id_uint8_val = src->id_uint8_val;
    dst->id_int16_val = src->id_int16_val;
    dst->id_uint16_val = src->id_uint16_val;
    dst->id_int32_val = src->id_int32_val;
    dst->id_uint32_val = src->id_uint32_val;
    dst->id_int64_val = src->id_int64_val;
    dst->id_uint64_val = src->id_uint64_val;
    dst->id_float_val = src->id_float_val;
    dst->id_double_val = src->id_double_val;
    dst->id_str_val = src->id_str_val;
    dst->id_vec_val = src->id_vec_val;
    dst->id_dict_val = src->id_dict_val;
    do
    {
        if (!rb_set_bool(&src->bool_val, &dst->bool_val)) break;
        if (!rb_set_int8(&src->int8_val, &dst->int8_val)) break;
        if (!rb_set_uint8(&src->uint8_val, &dst->uint8_val)) break;
        if (!rb_set_int16(&src->int16_val, &dst->int16_val)) break;
        if (!rb_set_uint16(&src->uint16_val, &dst->uint16_val)) break;
        if (!rb_set_int32(&src->int32_val, &dst->int32_val)) break;
        if (!rb_set_uint32(&src->uint32_val, &dst->uint32_val)) break;
        if (!rb_set_int64(&src->int64_val, &dst->int64_val)) break;
        if (!rb_set_uint64(&src->uint64_val, &dst->uint64_val)) break;
        if (!rb_set_float(&src->float_val, &dst->float_val)) break;
        if (!rb_set_double(&src->double_val, &dst->double_val)) break;
        if (!rb_set_string(&src->str_val, &dst->str_val)) break;
        if (!rb_set_int32_array(&src->vec_val, &dst->vec_val)) break;
        if (!rb_set_string_dict(&src->dict_val, &dst->dict_val)) break;

        return true;
    } while (0);

    return false;
}

rb_bool_t rb_eq_perf_object(const perf_object_t * src, const perf_object_t * dst)
{
    if (!src || !dst)
    {
        return false;
    }
    do
    {
        if (!rb_eq_bool(&src->bool_val, &dst->bool_val)) break;
        if (!rb_eq_int8(&src->int8_val, &dst->int8_val)) break;
        if (!rb_eq_uint8(&src->uint8_val, &dst->uint8_val)) break;
        if (!rb_eq_int16(&src->int16_val, &dst->int16_val)) break;
        if (!rb_eq_uint16(&src->uint16_val, &dst->uint16_val)) break;
        if (!rb_eq_int32(&src->int32_val, &dst->int32_val)) break;
        if (!rb_eq_uint32(&src->uint32_val, &dst->uint32_val)) break;
        if (!rb_eq_int64(&src->int64_val, &dst->int64_val)) break;
        if (!rb_eq_uint64(&src->uint64_val, &dst->uint64_val)) break;
        if (!rb_eq_float(&src->float_val, &dst->float_val)) break;
        if (!rb_eq_double(&src->double_val, &dst->double_val)) break;
        if (!rb_eq_string(&src->str_val, &dst->str_val)) break;
        if (!rb_eq_int32_array(&src->vec_val, &dst->vec_val)) break;
        if (!rb_eq_string_dict(&src->dict_val, &dst->dict_val)) break;

        return true;
    } while (0);

    return false;
}

void rb_dispose_perf_object(perf_object_t * obj_val)
{
    if (!obj_val)
    {
        return;
    }
    rb_dispose_bool(&obj_val->bool_val);
    rb_dispose_int8(&obj_val->int8_val);
    rb_dispose_uint8(&obj_val->uint8_val);
    rb_dispose_int16(&obj_val->int16_val);
    rb_dispose_uint16(&obj_val->uint16_val);
    rb_dispose_int32(&obj_val->int32_val);
    rb_dispose_uint32(&obj_val->uint32_val);
    rb_dispose_int64(&obj_val->int64_val);
    rb_dispose_uint64(&obj_val->uint64_val);
    rb_dispose_float(&obj_val->float_val);
    rb_dispose_double(&obj_val->double_val);
    rb_dispose_string(&obj_val->str_val);
    rb_dispose_int32_array(&obj_val->vec_val);
    rb_dispose_string_dict(&obj_val->dict_val);
}

rb_field_size_t rb_fields_perf_object(const perf_object_t * obj_val)
{
    rb_field_size_t fields = 0;
    if (!obj_val->skip_bool_val) ++fields;
    if (!obj_val->skip_int8_val) ++fields;
    if (!obj_val->skip_uint8_val) ++fields;
    if (!obj_val->skip_int16_val) ++fields;
    if (!obj_val->skip_uint16_val) ++fields;
    if (!obj_val->skip_int32_val) ++fields;
    if (!obj_val->skip_uint32_val) ++fields;
    if (!obj_val->skip_int64_val) ++fields;
    if (!obj_val->skip_uint64_val) ++fields;
    if (!obj_val->skip_float_val) ++fields;
    if (!obj_val->skip_double_val) ++fields;
    if (!obj_val->skip_str_val) ++fields;
    if (!obj_val->skip_vec_val) ++fields;
    if (!obj_val->skip_dict_val) ++fields;
    return fields;
}

rb_size_t rb_sizeof_perf_object(const perf_object_t * obj_val)
{
    rb_field_size_t fields = 0;
    rb_size_t size = 0;
    if (!obj_val->skip_bool_val)
    {
        size += rb_sizeof_bool(&obj_val->bool_val);
        ++fields;
    }
    if (!obj_val->skip_int8_val)
    {
        size += rb_sizeof_int8(&obj_val->int8_val);
        ++fields;
    }
    if (!obj_val->skip_uint8_val)
    {
        size += rb_sizeof_uint8(&obj_val->uint8_val);
        ++fields;
    }
    if (!obj_val->skip_int16_val)
    {
        size += rb_sizeof_int16(&obj_val->int16_val);
        ++fields;
    }
    if (!obj_val->skip_uint16_val)
    {
        size += rb_sizeof_uint16(&obj_val->uint16_val);
        ++fields;
    }
    if (!obj_val->skip_int32_val)
    {
        size += rb_sizeof_int32(&obj_val->int32_val);
        ++fields;
    }
    if (!obj_val->skip_uint32_val)
    {
        size += rb_sizeof_uint32(&obj_val->uint32_val);
        ++fields;
    }
    if (!obj_val->skip_int64_val)
    {
        size += rb_sizeof_int64(&obj_val->int64_val);
        ++fields;
    }
    if (!obj_val->skip_uint64_val)
    {
        size += rb_sizeof_uint64(&obj_val->uint64_val);
        ++fields;
    }
    if (!obj_val->skip_float_val)
    {
        size += rb_sizeof_float(&obj_val->float_val);
        ++fields;
    }
    if (!obj_val->skip_double_val)
    {
        size += rb_sizeof_double(&obj_val->double_val);
        ++fields;
    }
    if (!obj_val->skip_str_val)
    {
        size += rb_sizeof_string(&obj_val->str_val);
        ++fields;
    }
    if (!obj_val->skip_vec_val)
    {
        size += rb_sizeof_int32_array(&obj_val->vec_val);
        ++fields;
    }
    if (!obj_val->skip_dict_val)
    {
        size += rb_sizeof_string_dict(&obj_val->dict_val);
        ++fields;
    }
    size += rb_seek_field_table_item(fields);
    size += sizeof(rb_buf_end_t);
    return size;
}

rb_bool_t rb_encode_perf_object(const perf_object_t * obj_val, rb_buf_t * rb_val)
{
    rb_buf_t buf = rb_nested_buf(rb_val, 0);
    if (buf.size < 1)
    {
        return false;
    }
    do
    {
        rb_field_size_t fields = rb_fields_perf_object(obj_val);
        rb_field_size_t index = 0;
        if (!rb_set_field_count(fields, &buf)) break;

        if (!obj_val->skip_bool_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_bool_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_bool(&obj_val->bool_val, &buf)) break;
        }
        if (!obj_val->skip_int8_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_int8_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_int8(&obj_val->int8_val, &buf)) break;
        }
        if (!obj_val->skip_uint8_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_uint8_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_uint8(&obj_val->uint8_val, &buf)) break;
        }
        if (!obj_val->skip_int16_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_int16_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_int16(&obj_val->int16_val, &buf)) break;
        }
        if (!obj_val->skip_uint16_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_uint16_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_uint16(&obj_val->uint16_val, &buf)) break;
        }
        if (!obj_val->skip_int32_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_int32_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_int32(&obj_val->int32_val, &buf)) break;
        }
        if (!obj_val->skip_uint32_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_uint32_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_uint32(&obj_val->uint32_val, &buf)) break;
        }
        if (!obj_val->skip_int64_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_int64_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_int64(&obj_val->int64_val, &buf)) break;
        }
        if (!obj_val->skip_uint64_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_uint64_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_uint64(&obj_val->uint64_val, &buf)) break;
        }
        if (!obj_val->skip_float_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_float_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_float(&obj_val->float_val, &buf)) break;
        }
        if (!obj_val->skip_double_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_double_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_double(&obj_val->double_val, &buf)) break;
        }
        if (!obj_val->skip_str_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_str_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_string(&obj_val->str_val, &buf)) break;
        }
        if (!obj_val->skip_vec_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_vec_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_int32_array(&obj_val->vec_val, &buf)) break;
        }
        if (!obj_val->skip_dict_val)
        {
            if (!rb_set_field_table_item(index++, obj_val->id_dict_val, buf.pos - buf.start, &buf)) break;
            if (!rb_encode_string_dict(&obj_val->dict_val, &buf)) break;
        }

        if (!rb_set_buf_size(buf.pos - buf.start + sizeof(rb_buf_end_t), &buf)) break;
        if (!rb_encode_end(fields, &buf)) break;
        rb_val->pos = buf.pos;

        return true;
    } while (0);

    return false;
}

static rb_bool_t __decode_perf_object(
    const rb_field_table_item_t * item,
    const rb_buf_t * rb_val,
    perf_object_t * obj_val)
{
    if (item->id == obj_val->id_bool_val)
    {
        rb_bool_t rc = rb_decode_bool(rb_val, item->offset, &obj_val->bool_val);
        if (rc)
        {
            obj_val->rb_has_bool_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_int8_val)
    {
        rb_bool_t rc = rb_decode_int8(rb_val, item->offset, &obj_val->int8_val);
        if (rc)
        {
            obj_val->rb_has_int8_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_uint8_val)
    {
        rb_bool_t rc = rb_decode_uint8(rb_val, item->offset, &obj_val->uint8_val);
        if (rc)
        {
            obj_val->rb_has_uint8_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_int16_val)
    {
        rb_bool_t rc = rb_decode_int16(rb_val, item->offset, &obj_val->int16_val);
        if (rc)
        {
            obj_val->rb_has_int16_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_uint16_val)
    {
        rb_bool_t rc = rb_decode_uint16(rb_val, item->offset, &obj_val->uint16_val);
        if (rc)
        {
            obj_val->rb_has_uint16_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_int32_val)
    {
        rb_bool_t rc = rb_decode_int32(rb_val, item->offset, &obj_val->int32_val);
        if (rc)
        {
            obj_val->rb_has_int32_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_uint32_val)
    {
        rb_bool_t rc = rb_decode_uint32(rb_val, item->offset, &obj_val->uint32_val);
        if (rc)
        {
            obj_val->rb_has_uint32_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_int64_val)
    {
        rb_bool_t rc = rb_decode_int64(rb_val, item->offset, &obj_val->int64_val);
        if (rc)
        {
            obj_val->rb_has_int64_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_uint64_val)
    {
        rb_bool_t rc = rb_decode_uint64(rb_val, item->offset, &obj_val->uint64_val);
        if (rc)
        {
            obj_val->rb_has_uint64_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_float_val)
    {
        rb_bool_t rc = rb_decode_float(rb_val, item->offset, &obj_val->float_val);
        if (rc)
        {
            obj_val->rb_has_float_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_double_val)
    {
        rb_bool_t rc = rb_decode_double(rb_val, item->offset, &obj_val->double_val);
        if (rc)
        {
            obj_val->rb_has_double_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_str_val)
    {
        rb_bool_t rc = rb_decode_string(rb_val, item->offset, &obj_val->str_val);
        if (rc)
        {
            obj_val->rb_has_str_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_vec_val)
    {
        rb_bool_t rc = rb_decode_int32_array(rb_val, item->offset, &obj_val->vec_val);
        if (rc)
        {
            obj_val->rb_has_vec_val = true;
        }
        return rc;
    }
    if (item->id == obj_val->id_dict_val)
    {
        rb_bool_t rc = rb_decode_string_dict(rb_val, item->offset, &obj_val->dict_val);
        if (rc)
        {
            obj_val->rb_has_dict_val = true;
        }
        return rc;
    }
    return true;
}

rb_bool_t rb_decode_perf_object(const rb_buf_t * rb_val, rb_offset_t offset, perf_object_t * obj_val)
{
    if (!obj_val)
    {
        return false;
    }
    rb_buf_t buf = rb_nested_buf(rb_val, offset);
    if (buf.size < 1)
    {
        return false;
    }
    rb_field_table_head_t head = rb_get_field_table_head(&buf);
    if (head.fields < 1 || !rb_check_code(&buf, &head))
    {
        return false;
    }
    rb_field_table_item_t item = { 0, 0 };
    rb_field_size_t i = 0;
    for (i = 0; i < head.fields; ++i)
    {
        if (!rb_get_field_table_item(i, &buf, &item))
        {
            return false;
        }
        if (item.offset >= head.size)
        {
            return false;
        }
        if (item.offset > 0 && !__decode_perf_object(&item, &buf, obj_val))
        {
            return false;
        }
    }
    return true;
}

static rb_bool_t __dump_perf_object(const void * obj_val, rb_buf_t * buf)
{
    return rb_encode_perf_object((perf_object_t *) obj_val, buf);
}

rb_bool_t rb_dump_perf_object(const perf_object_t * obj_val, const char * path)
{
    if (!obj_val || !path)
    {
        return false;
    }
    rb_size_t size = rb_sizeof_perf_object(obj_val);
    if (size < 1)
    {
        return false;
    }
    return rb_dump_buf(__dump_perf_object, obj_val, size, path);
}

static rb_bool_t __load_perf_object(const rb_buf_t * buf, void * obj_val)
{
    return rb_decode_perf_object(buf, 0, (perf_object_t *) obj_val);
}

rb_bool_t rb_load_perf_object(const char * path, perf_object_t * obj_val)
{
    return rb_load_buf(path, __load_perf_object, obj_val);
}
